# Help: rename the adject docker-compose.override.example.yml file to docker-compose.override.yml
#       then in the override file uncomment the environment tag for the collectors you want to
#       run. Then add the environment vars you want to use.
version: '3.6'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: "mongo"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
  
  api:
    image: bonganim911/bongz-hygieia-api:0.1
    depends_on:
      - mongodb
    links:
      - mongodb
    ports:
      - "8080:8080"

  ui:
    image: bonganim911/hygieia-ui:0.1
    depends_on:
      - api
    ports:
      - "3000:80"

  jenkins-build-collector:
    image: bonganim911/hygieai-jenkins:0.1
    env_file:
      - jenkins.env
     # environment:
     # - JENKINS_HOST=http://192.168.1.148:9000
     # - JENKINS_USERNAME=bonganim911
     # - JENKINS_API_KEY=1756366e53c6d671795d3dcde484a3ad2
     # - JENKINS_CRON=0 0/5 * * * *
    depends_on:
      - mongodb
      - api
    links:
      - mongodb
      - api

  bitbucket-collector:
    image: bonganim911/hygieai-bitbucket:0.1
    env_file:
      - bitbucket.env
    depends_on:
      - mongodb
      - api
    links:
      - mongodb
      - api


  # jira-collector:
  #   image: hygieia-jira-feature-collector
  #  environment:
        # you can override these by creating a docker-compose.overider.yml and put in entries like this:
        #REQUIRED Entries
  #    - JIRA_BASE_URL=https://jira.atlassian.com
        #64-bit encoded credentials with the pattern username:password
        #on a mac you con create them with : echo "username:password" | base64
        #reference:  https://www.base64decode.org/
  #    - JIRA_CREDENTIALS=username:password
  #   depends_on:
  #     - mongodb
  #      - api
  #   links:
  #     - mongodb
  #     - api

  # sonar-codequality-collector:
  #   image: hygieia-sonar-codequality-collector
  #  environment:
  #  - SONAR_CRON=0 0/5 * * * *
  #  - SONAR_URL=http://localhost:9000
  #   depends_on:
  #     - mongodb
  #      - api
  #   links:
  #     - mongodb
  #      - api


  # udeploy-collector:
  #   image: hygieia-udeploy-collector:0.1
  #   volumes:
  #   - ./logs:/hygieia/logs
  #   links:
  #   - mongodb
  #   - api
  #   environment:
  #UDeploy server (required) - Can provide multiple
  #  - UDEPLOY_URL:-http://udeploy.company.com
  #UDeploy user name (required)
  #  - UDEPLOY_USERNAME:-bobama
  #UDeploy password (required)
  #  - UDEPLOY_PASSWORD:-s3cr3t
  #Collector schedule (required)
  #  - UDEPLOY_CRON:-0 0/5 * * * *